Let's upload the data file on our Notebook

In [10]:
from google.colab import files

In [11]:
file_read = files.upload()

Saving makeSenseOfCensus.csv to makeSenseOfCensus (1).csv


Step 1 : Read the Data!

In [12]:
data = "makeSenseOfCensus.csv"

Importing Numpy dependency and generate the dataset into n-dimensional Array

In [13]:
import numpy as np
data_np = np.genfromtxt(data, delimiter = ",", skip_header = 1)
print(data_np)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [14]:
type(data_np)

numpy.ndarray

In [15]:
print("\nData: \n\n", data_np)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [16]:
print(data_np.shape)

(1000, 8)


In [17]:
print(data_np.dtype)

float64


In [18]:
new_record = np.array([[50, 9, 4, 1, 0, 0, 40, 0]], dtype="float64")

In [19]:
print(new_record.shape)

(1, 8)


Step 2 : Append the Data

In [20]:

New_data = np.append(data_np, new_record, axis=0)
print(New_data.shape)

(1001, 8)


Step 3 : Check if it's a young country or old country

In [21]:
#Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.
age_arr = New_data[:, 0]

In [22]:


# Find the max age and store it in a variable called 'max_age'.
age_arr = New_data[:, 0]
max_age = np.max(age_arr)
print("Max Age: ", max_age)
# Find the min age and store it in a variable called 'min_age'.
min_age = np.min(age_arr)
print("Min Age: ", min_age)
# Find the mean of the age and store it in a variable called 'age_mean'.
age_mean = np.mean(age_arr)
print("Mean Age: ", age_mean)
# Find the standard deviation of the age and store it in a variable called 'age_std'
std_age = np.std(age_arr)
print("Standard deviation Age:", std_age)


Max Age:  90.0
Min Age:  17.0
Mean Age:  38.06293706293706
Standard deviation Age: 13.341478176165857


Step 4: Let's check the country's race distribution to identify the minorities

In [23]:

race_arr = New_data[:, 2]
print(race_arr)

[4. 4. 4. ... 4. 4. 4.]


In [24]:
np.unique(race_arr) #Checking out for all the unique values in the race array

array([0., 1., 2., 3., 4.])

In [25]:
# Create four different arrays by subsetting 'census' array by Race 
# column(Race is the column with index 2) and save them in 'race_0','race_1', 
# 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array
#  where 'race'column has value 0 in 'race_0', so on and so forth)
race_0 = race_arr[race_arr == 0]
race_1 = race_arr[race_arr == 1]
race_2 = race_arr[race_arr == 2]
race_3 = race_arr[race_arr == 3]
race_4 = race_arr[race_arr == 4]

In [26]:
# Store the length of the above created arrays in
#  'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

#Amer-Indian-Eskimo
len_0 = np.size(race_0)
print("Length of race 0: ", len_0)

#Asian-Pac-Islander
len_1 = np.size(race_1)
print("Length of race 1: ", len_1)

#Black
len_2 = np.size(race_2)
print("Length of race 2: ", len_2)

#others
len_3 = np.size(race_3)
print("Length of race 3: ", len_3)

#White
len_4 = np.size(race_4)
print("Length of race 4: ", len_4)

Length of race 0:  10
Length of race 1:  27
Length of race 2:  110
Length of race 3:  6
Length of race 4:  848


In [27]:
print(f"race others is  with just {len_3} number of citizens ", )

race others is  with just 6 number of citizens 


In [28]:
minority_race = len_3 # size of the race with least number of citizens
print(minority_race)

6


Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

In [29]:
senior_citizens = age_arr[age_arr > 60] #Using the age array which we created earlier and filtering out the senior citizens above the age of 60
print(senior_citizens)

[79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]


In [30]:
senior_wh =  New_data[:, 6] #pulling out the working hours of senior citizens using the array having the condition >60
print(senior_wh[age_arr>60])
working_hours_sum = np.sum(senior_wh[age_arr>60])
print("Total working hours of all the senior citizens", working_hours_sum)


[20.  2. 40. 40. 40. 40.  2. 20. 20. 40. 40. 50. 20. 40. 40. 40. 16. 40.
 24. 10. 45. 55.  8. 40. 40. 40. 24. 24. 35. 20. 40.  9. 48. 40. 40. 30.
 24. 15. 15.  4. 59. 50. 40. 20. 40. 45. 40. 40. 24.  6. 48. 40. 40. 15.
 55. 40. 30.  5. 40. 40. 20.]
Total working hours of all the senior citizens 1917.0


In [31]:
# Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'
senior_citizens_len = np.size(senior_wh[age_arr>60])
print(senior_citizens_len)

61


In [32]:
# Finally find the average working hours of the senior citizens by dividing 
# 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.
avg_working_hours = working_hours_sum / senior_citizens_len
print(avg_working_hours)
print("Hence the policy is not followed")

31.42622950819672
Hence the policy is not followed


Step 6: Let's check that higher educated people have better pay in general.

In [33]:
# Create two new subset arrays called 'high' and 'low' by filtering 'census' 
# according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.


edu_num = New_data[:, 1]
print(edu_num)

high = edu_num[edu_num>10]
low = edu_num[edu_num<=10]

[13. 13.  9. ... 10. 13.  9.]


In [34]:
# Find the mean of income column(income is the column with index 7) 
# of 'high' array and store it in 'avg_pay_high'. 
income_arr = New_data[:, 7]
avg_pay_high = np.mean(income_arr[income_arr == 1]) #since in data >50 is 1 we pull out all the 1's and calculate mean

print(avg_pay_high)

1.0


In [35]:
# Do the same for 'low' array and store it's mean in 'avg_pay_low'.
avg_pay_low = np.mean(income_arr[income_arr == 0])
print(avg_pay_low)

0.0
